### PR TITLE
added serve task

### PR DESCRIPTION
**Pull request by rodrigogs**

### CODE REVIEW

**Comment by danielrohers** [comment]
What's the difference of `npm start`?

**Comment by rodrigogs** [comment]
For cloud environments like c9.io, http servers that doesn't accept IP and PORT are useless.

**Comment by danielrohers** [comment]
sure!
1. `gulp.src('./')` must be `gulp.src('./dist')`
2. the idea is to be a preview, then `directoryListing: false`
3. remove http-server on `package.json`
4. update `npm start` to use`gulp serve`
5. update `README.md` with two options (gulp && npm)

**Comment by rodrigogs** [comment]
meeh

I just did it cuz I was going to use your project to create a site of mine.

Ain't got no time for that.

**Comment by danielrohers** [comment]
aff... so simple!

I requested it to accept the full pull-request

**Comment by rodrigogs** [comment]
Maybe later. I'm reoppening the thread.

**Comment by danielrohers** [comment]
will merge and adjustments

**Comment by rodrigogs** [comment]
ty o7

dont forget my birthday bbq tonight ;D

**Comment by danielrohers** [comment]
;D

**Pull request merged**
